export const courses = [
    {
        id: 1,
        image: "/assets/picture/Blockchain.jpg",
        title: "Blockchain Fundamentals for Beginners",
        university: "Kasetsart University",
        date: "Oct 15, 2025",
        time: "9:30 AM – 12:00 PM",
        location: "Online Event",
        seats: 50,
        price: 299,
        currency: "THB",
        sponsored: true,
        extensionAvailable: true,
        bookmarked: false,
        registered: true,
        history: true
    },
    {
        id: 2,
        image: "/assets/picture/Blockchain.jpg",
        title: "Introduction to Artificial Intelligence",
        university: "Chulalongkorn University",
        date: "Nov 2, 2025",
        time: "1:00 PM – 4:00 PM",
        location: "Bangkok",
        seats: 120,
        price: 499,
        currency: "THB",
        sponsored: false,
        extensionAvailable: true,
        bookmarked: true,
        registered: false,
        history: true
    },
    {
        id: 3,
        image: "/assets/picture/Webdev.jpg",
        title: "Cybersecurity Essentials",
        university: "KMUTT",
        date: "Dec 1, 2025",
        time: "10:00 AM – 1:00 PM",
        location: "Online Event",
        seats: 80,
        price: 399,
        currency: "THB",
        sponsored: true,
        extensionAvailable: false,
        bookmarked: false,
        registered: true,
        history: true
    },
    {
        id: 4,
        image: "/assets/picture/Blockchain.jpg",
        title: "Modern Fullstack Web Development",
        university: "Thammasat University",
        date: "Oct 28, 2025",
        time: "6:00 PM – 9:00 PM",
        location: "Pathum Thani",
        seats: 70,
        price: 699,
        currency: "THB",
        sponsored: false,
        extensionAvailable: true,
        bookmarked: true,
        registered: true,
        history: true
    },
    {
        id: 5,
        image: "/assets/picture/Blockchain.jpg",
        title: "UI/UX Design Bootcamp",
        university: "Mahidol University",
        date: "Nov 10, 2025",
        time: "9:00 AM – 3:00 PM",
        location: "Bangkok",
        seats: 40,
        price: 899,
        currency: "THB",
        sponsored: false,
        extensionAvailable: false,
        bookmarked: false,
        registered: false,
        history: false
    },
    {
        id: 6,
        image: "/assets/picture/Blockchain.jpg",
        title: "Data Science with Python",
        university: "KKU",
        date: "Jan 5, 2026",
        time: "8:30 AM – 12:00 PM",
        location: "Online Event",
        seats: 90,
        price: 550,
        currency: "THB",
        sponsored: true,
        extensionAvailable: true,
        bookmarked: false,
        registered: false,
        history: false
    },
    {
        id: 7,
        image: "/assets/picture/Blockchain.jpg",
        title: "Cloud Computing Fundamentals",
        university: "AIT",
        date: "Feb 12, 2026",
        time: "2:00 PM – 5:00 PM",
        location: "Pathum Thani",
        seats: 65,
        price: 450,
        currency: "THB",
        sponsored: false,
        extensionAvailable: true,
        bookmarked: true,
        registered: true,
        history: true
    },
    {
        id: 8,
        image: "/assets/picture/Blockchain.jpg",
        title: "Game Development with Unity",
        university: "Silpakorn University",
        date: "Mar 8, 2026",
        time: "11:00 AM – 4:00 PM",
        location: "Online Event",
        seats: 55,
        price: 799,
        currency: "THB",
        sponsored: true,
        extensionAvailable: false,
        bookmarked: false,
        registered: true,
        history: true
    },
    {
        id: 9,
        image: "/assets/picture/Blockchain.jpg",
        title: "DevOps and CI/CD Workshop",
        university: "KMITL",
        date: "Apr 2, 2026",
        time: "1:00 PM – 6:00 PM",
        location: "Bangkok",
        seats: 45,
        price: 650,
        currency: "THB",
        sponsored: false,
        extensionAvailable: true,
        bookmarked: true,
        registered: true,
        history: false
    },
    {
        id: 10,
        image: "/assets/picture/Blockchain.jpg",
        title: "Flutter Mobile App Development",
        university: "Burapha University",
        date: "May 14, 2026",
        time: "10:00 AM – 2:00 PM",
        location: "Online Event",
        seats: 100,
        price: 350,
        currency: "THB",
        sponsored: true,
        extensionAvailable: true,
        bookmarked: false,
        registered: false,
        history: true
    },
    {
        id: 11,
        image: "/assets/picture/Blockchain.jpg",
        title: "Machine Learning for Everyone",
        university: "KKU",
        date: "Jun 20, 2026",
        time: "9:00 AM – 12:00 PM",
        location: "Khon Kaen",
        seats: 75,
        price: 599,
        currency: "THB",
        sponsored: false,
        extensionAvailable: false,
        bookmarked: false,
        registered: false,
        history: false
    },
    {
        id: 12,
        image: "/assets/picture/Blockchain.jpg",
        title: "Networking Basics and Routing",
        university: "Prince of Songkla University",
        date: "Jul 7, 2026",
        time: "3:00 PM – 6:00 PM",
        location: "Hat Yai",
        seats: 35,
        price: 420,
        currency: "THB",
        sponsored: true,
        extensionAvailable: false,
        bookmarked: true,
        registered: true,
        history: true
    },
    {
        id: 13,
        image: "/assets/picture/Blockchain.jpg",
        title: "IoT Systems and Smart Devices",
        university: "KMUTNB",
        date: "Aug 18, 2026",
        time: "8:00 AM – 11:30 AM",
        location: "Online Event",
        seats: 60,
        price: 480,
        currency: "THB",
        sponsored: false,
        extensionAvailable: true,
        bookmarked: false,
        registered: true,
        history: false
    },
    {
        id: 14,
        image: "/assets/picture/Blockchain.jpg",
        title: "AR/VR Experience Design",
        university: "Srinakharinwirot University",
        date: "Sep 3, 2026",
        time: "1:00 PM – 5:00 PM",
        location: "Bangkok",
        seats: 25,
        price: 990,
        currency: "THB",
        sponsored: true,
        extensionAvailable: false,
        bookmarked: false,
        registered: true,
        history: false
    },
    {
        id: 15,
        image: "/assets/picture/Blockchain.jpg",
        title: "FinTech and Digital Payments",
        university: "NIDA",
        date: "Oct 25, 2026",
        time: "9:30 AM – 1:30 PM",
        location: "Online Event",
        seats: 110,
        price: 720,
        currency: "THB",
        sponsored: false,
        extensionAvailable: true,
        bookmarked: true,
        registered: true,
        history: true
    },
];